<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.bank</groupId>
    <artifactId>banking-app</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <artifactId>banking-service</artifactId>
  <dependencies>

        <!-- ══════════════════════════════════════════════════
             Modules internes
        ═══════════════════════════════════════════════════════ -->
        <dependency>
            <groupId>com.bank</groupId>
            <artifactId>banking-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.bank</groupId>
            <artifactId>banking-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.bank</groupId>
            <artifactId>banking-infrastructure</artifactId>
        </dependency>
		<dependency>
            <groupId>com.bank</groupId>
            <artifactId>banking-security</artifactId>
        </dependency>
        <!-- ══════════════════════════════════════════════════
             Persistance — Spring Data JPA + Hibernate + PostgreSQL
        ═══════════════════════════════════════════════════════ -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
		    <groupId>org.springframework.boot</groupId>
		    <artifactId>spring-boot-starter-security</artifactId>
		</dependency>
	</dependencies>
</project>